/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasteleria;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauricio
 */
public class DetalleVenta extends javax.swing.JFrame {

    /**
     * Creates new form DetalleBoleta
     */
    public DetalleVenta(int correlativo, String tipo) {
        initComponents();
        llenarTabla(correlativo,tipo);
    }

    
    public void llenarTabla(int correlativo, String tipo){
        MySQL my = new MySQL();
        Connection con = my.getConnection();
        Statement sql;
        
        try {
            sql = con.createStatement();
        
        
             PreparedStatement stmt = con.prepareStatement("SELECT * FROM ventaDetalle WHERE correlativo = ? AND tipo = ?");
             stmt.setInt(1,correlativo);
             stmt.setString(2,tipo);
             
				ResultSet rs;
                                rs = stmt.executeQuery();
                                
				boolean r=rs.next();
				while (r) {
                                    
                                   
                                    
                                    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

                                       
                                    Object [] fila=new Object[5];
                                    
                                    fila[0]=rs.getDouble("cantidad");
                                    fila[1]=rs.getString("codigoProducto");
                                    fila[2]=llenarNombre(rs.getString("codigoProducto"));
                                    fila[3]=rs.getInt("unitario");
                                    fila[4]=rs.getInt("total");;
                                    
                                 
                                    
                                 
                                    modelo.addRow(fila);

                                    tabla.setModel(modelo); 
                                    
                                    r=rs.next();
                                    }
        } catch (SQLException ex) {
            Logger.getLogger(Pedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    public String llenarNombre(String codigo){
        MySQL my = new MySQL();
        Connection con = my.getConnection();
        Statement sql;
        
        try {
            sql = con.createStatement();
        
        
             PreparedStatement stmt = con.prepareStatement("SELECT * FROM productos WHERE codigo = ?");
             stmt.setString(1,codigo);
				ResultSet rs;
                                rs = stmt.executeQuery();
                                String n = "";
				boolean r=rs.next();
				while (r) {
                                    
                                    n = rs.getString("nombre");
                                    r=rs.next();
                                    
                                    }
                                return n;
        } catch (SQLException ex) {
        }
        return "";
    }
    public int llenarPrecio(String codigo){
        MySQL my = new MySQL();
        Connection con = my.getConnection();
        Statement sql;
        
        try {
            sql = con.createStatement();
        
        
             PreparedStatement stmt = con.prepareStatement("SELECT * FROM productos WHERE codigo = ?");
             stmt.setString(1,codigo);
				ResultSet rs;
                                rs = stmt.executeQuery();
                                int n = 0;
				boolean r=rs.next();
				while (r) {
                                    
                                    
                                    n= rs.getInt("total");
                                    r=rs.next();
                                    
                                    }
                                return n;
        } catch (SQLException ex) {
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Nombre", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 800, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 80, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FondoDetalleVenta.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1040, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleVenta(0,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
